services:
  db:
    image: postgres:15-alpine
    container_name: meal-manager-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meal_manager
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

# Removed named volume section as we are using bind mount
